
# ★ Systems Of Equations ★

In [1]:
# Import modules
import sys
import numpy as np
from scipy import linalg

# 2.1 Gaussian Elimination

In [5]:
def naive_gaussian_elimination(matrix):
    """
    A simple gaussian elimination to solve equations
    
    Args:
        matrix : numpy 2d array
        
    Returns:
        mat : The matrix processed by gaussian elimination
        x   : The roots of the equation
        
    Raises:
        ValueError:
            - matrix is null
        RuntimeError :
            - Zero pivot encountered
    """
    if matrix is None :
        raise ValueError('args matrix is null')
    
    #Clone the matrix
    mat = matrix.copy()
    
    # Row Size
    n = mat.shape[0]
    
    # Column Size
    m = mat.shape[1]
    
    # Gaussian Elimaination
    for j in xrange(0, n):
        if abs(mat[j , j]) == 0 :
            raise RuntimeError('zero pivot encountered')
        for i in xrange(j + 1, n):
            mult = mat[i, j] / mat[j, j]
            for k in xrange(j,m):
                mat[i, k] = mat[i, k] - mult * mat[j, k]
    
    # Back Substitution
    x = np.zeros(n, dtype=np.float)
    for i in xrange(n - 1,-1,-1):
        for j in xrange(i + 1, n):
            mat[i, m-1] = mat[i ,m-1] - mat[i,j] * x[j]
        x[i] = mat[i, m-1] / mat[i, i]
        
    return mat, x

### Example
Solve equations
\begin{matrix}
x + 2y - z = 3 & \\ 
2x + y - 2z = 3 & \\ 
-3x + y + z = -6 
\end{matrix}

In [6]:
"""
Input:
[[ 1  2 -1  3]
 [ 2  1 -2  3]
 [-3  1  1 -6]]
"""
input_mat = np.array([ 1, 2, -1, 3, 2, 1, -2, 3, -3, 1, 1, -6],dtype=np.float)
input_mat = input_mat.reshape(3, 4)
output_mat, x = naive_gaussian_elimination(input_mat)
print('----------------------')
print(output_mat)
print('----------------------')
print(x)

----------------------
[[ 1.  2. -1.  3.]
 [ 0. -3.  0. -3.]
 [ 0.  0. -2. -4.]]
----------------------
[ 3.  1.  2.]


# 2.2 The LU Factorization

### Example
Solve system
\begin{matrix}
x + 2y - z = 3 & \\ 
2x + y - 2z = 3 & \\ 
-3x + y + z = -6 
\end{matrix}
 
 using the LU factorization

In [11]:
A = np.array([ 1, 2, -1, 2, 1, -2, -3, 1, 1],dtype=np.float)
A = A.reshape(3, 3)
lu, piv = linalg.lu_factor(A)

b = np.array([3, 3, -6])
sol = linalg.lu_solve([lu, piv], b)
print(sol)

[ 3.  1.  2.]


### Example
Find the LU factorization of the given matrices. Check by matrix multiplication

$$
\begin{bmatrix}
3 & 1 & 2 \\ 
6 & 3 & 4 \\ 
3 & 1 & 5
\end{bmatrix}
$$

In [24]:
A = np.array([3, 1, 2, 6, 3, 4, 3, 1, 5], dtype=np.float).reshape(3,3)
P, L, U = linalg.lu(A)
print(A)
print('--------------------')
print(L)
print('--------------------')
print(U)
print('--------------------')
print(np.matmul(P,np.matmul(L, U)))

[[ 3.  1.  2.]
 [ 6.  3.  4.]
 [ 3.  1.  5.]]
--------------------
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5  1.   1. ]]
--------------------
[[ 6.   3.   4. ]
 [ 0.  -0.5  0. ]
 [ 0.   0.   3. ]]
--------------------
[[ 3.  1.  2.]
 [ 6.  3.  4.]
 [ 3.  1.  5.]]


### Example
Solve the system by LU factorization

$$
\begin{bmatrix}
3 & 1 & 2 \\ 
6 & 3 & 4 \\ 
3 & 1 & 5
\end{bmatrix}
\begin{bmatrix}
x_1 \\ 
x_2 \\ 
x_3
\end{bmatrix}
=
\begin{bmatrix}
0 \\ 
1 \\ 
3
\end{bmatrix}
$$

In [25]:
A = np.array([3, 1, 2, 6, 3, 4, 3, 1, 5], dtype=np.float).reshape(3,3)
b = np.array([0, 1, 3])
lu, piv = linalg.lu_factor(A)
x = linalg.lu_solve(A, b)

ValueError: too many values to unpack