# ★ Least Squares ★

In [1]:
# Import modules
import sys
import math
import numpy as np
from matplotlib import pyplot as plt
from scipy import linalg

# 4.1 Least Squares and the normal equations

$$
A^TA\bar{X} = A^Tb
$$

for the least squares solution $\bar{x}$ that minimizes the Euclidean length if the residual $r = b -Ax$

### Example 
Solve the least squares problem 
$$
\begin{bmatrix}
1 & -4 \\ 
2 & 3  \\ 
2 & 2
\end{bmatrix}
\begin{bmatrix}
x_1 \\ 
x_2
\end{bmatrix}
=
\begin{bmatrix}
-3 \\ 
15 \\
9
\end{bmatrix}
$$

In [10]:
A = np.array([1, -4, 2, 3, 2, 2]).reshape(3, 2)
b = np.array([-3, 15, 9])
x = linalg.lstsq(A, b)
print(x[0])

[ 3.8  1.8]


### Example
Find the line that best fits the three data points (t,y)=(1,2),(-1,1) and (1,3) <br/>
The model is $y = c_1 + c_2t$

In [3]:
A = np.array([1, 1, 1, -1, 1, 1]).reshape(3, 2)
b = np.array([2, 1, 3])
x = linalg.lstsq(A, b)
print(x[0])

[ 1.75  0.75]


The best line is $y = \frac{7}{4} + \frac{3}{4}t$ 

# 4.3 QR Factorization

In [81]:
def classical_gram_schmidt_orthogonalization(A):
    Q = np.zeros(A.size).reshape(A.shape)
    R = np.zeros(A.shape[1] ** 2).reshape(A.shape[1], A.shape[1])
    for j in range(A.shape[1]):
        y = A[:,j]
        for i in range(j):
            R[i][j] = np.matmul(Q[:,i], A[:,j])
            y = y - R[i][j] * Q[:,i]
        R[j][j] = linalg.norm(y, 2)
        Q[:,j] = y / R[j][j]
    return Q, R

### Example
Find the reduced QR factorization by applying Gram-Schmidt orthogonalization to the columns of 
$
A = 
\begin{bmatrix}
1 & -4 \\ 
2 & 3  \\ 
2 & 2
\end{bmatrix}
$

In [82]:
A = np.array([1, -4, 2, 3, 2, 2]).reshape(3, 2)
Q, R = classical_gram_schmidt_orthogonalization(A)
print('Q =')
print(Q)
print('R =')
print(R)

Q =
[[ 0.33333333 -0.93333333]
 [ 0.66666667  0.33333333]
 [ 0.66666667  0.13333333]]
R =
[[ 3.  2.]
 [ 0.  5.]]


### Example
Find the full QR factorization of 
$
A = 
\begin{bmatrix}
1 & -4 \\ 
2 & 3  \\ 
2 & 2
\end{bmatrix}
$

In [146]:
A = np.array([1, -4, 2, 3, 2, 2]).reshape(3, 2)
Q, R = linalg.qr(A)
print('Q =')
print(Q)
print('R =')
print(R)

Q =
[[-0.33333333  0.93333333 -0.13333333]
 [-0.66666667 -0.33333333 -0.66666667]
 [-0.66666667 -0.13333333  0.73333333]]
R =
[[-3. -2.]
 [ 0. -5.]
 [ 0.  0.]]


### Example 
Use the full QR factorization to solve the least squares problem
$$
\begin{bmatrix}
1 & -4 \\ 
2 & 3  \\ 
2 & 2
\end{bmatrix}
\begin{bmatrix}
x_1 \\ 
x_2
\end{bmatrix}
=
\begin{bmatrix}
-3 \\ 
15 \\
9
\end{bmatrix}
$$

In [204]:
A = np.array([1, -4, 2, 3, 2, 2]).reshape(3, 2)
b = np.array([-3, 15, 9]).T
Q, R = linalg.qr(A)
lu, piv = linalg.lu_factor(R[:2,:])
x = linalg.lu_solve([lu, piv], np.matmul(Q.T, b).reshape(3, 1)[:2])
print('x = %s' %x.T)

x = [[ 3.8  1.8]]


## Modified Gram-Schmidt orthogonalization